// This file has been automatically generaded.
// Please do not make changes.

#include <avr/pgmspace.h>
#include "KeyboardMap.h"

char keyString0[] PROGMEM = "\033[3~";
char keyString1[] PROGMEM = "\033Om";
char keyString2[] PROGMEM = "\033[[A";
char keyString3[] PROGMEM = "\033[23~";
char keyString4[] PROGMEM = "\033[[B";
char keyString5[] PROGMEM = "\033[24~";
char keyString6[] PROGMEM = "\033[[C";
char keyString7[] PROGMEM = "\033[25~";
char keyString8[] PROGMEM = "\033[[D";
char keyString9[] PROGMEM = "\033[26~";
char keyString10[] PROGMEM = "\033[[E";
char keyString11[] PROGMEM = "\033[28~";
char keyString12[] PROGMEM = "\033[17~";
char keyString13[] PROGMEM = "\033[29~";
char keyString14[] PROGMEM = "\033[18~";
char keyString15[] PROGMEM = "\033[31~";
char keyString16[] PROGMEM = "\033[19~";
char keyString17[] PROGMEM = "\033[32~";
char keyString18[] PROGMEM = "\033[20~";
char keyString19[] PROGMEM = "\033[33~";
char keyString20[] PROGMEM = "\033[21~";
char keyString21[] PROGMEM = "\033[34~";
char keyString22[] PROGMEM = "\033OP";
char keyString23[] PROGMEM = "\033Ow";
char keyString24[] PROGMEM = "\033Ox";
char keyString25[] PROGMEM = "\033Oy";
char keyString26[] PROGMEM = "\033OS";
char keyString27[] PROGMEM = "\033Ot";
char keyString28[] PROGMEM = "\033Ou";
char keyString29[] PROGMEM = "\033Ov";
char keyString30[] PROGMEM = "\033OM";
char keyString31[] PROGMEM = "\033Oq";
char keyString32[] PROGMEM = "\033Or";
char keyString33[] PROGMEM = "\033Os";
char keyString34[] PROGMEM = "\033Op";
char keyString35[] PROGMEM = "\033On";
char keyString36[] PROGMEM = "\033Ol";
char keyString37[] PROGMEM = "\033[1~";
char keyString38[] PROGMEM = "\033[A";
char keyString39[] PROGMEM = "\033[5~";
char keyString40[] PROGMEM = "\033[D";
char keyString41[] PROGMEM = "\033[C";
char keyString42[] PROGMEM = "\033[4~";
char keyString43[] PROGMEM = "\033[B";
char keyString44[] PROGMEM = "\033[6~";
char keyString45[] PROGMEM = "\033[2~";

struct KeyMap keys[] PROGMEM =
{
  { KEYCODE_MINUS, MODIFIER_SHIFT | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1f } },
  { KEYCODE_BKSP, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x08 } },
  { KEYCODE_E, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000e } },
  { KEYCODE_A, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000a } },
  { KEYCODE_D, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000d } },
  { KEYCODE_F, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000f } },
  { KEYCODE_C, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000c } },
  { KEYCODE_B, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x000b } },
  { KEYCODE_KP_7, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0007 } },
  { KEYCODE_KP_8, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0008 } },
  { KEYCODE_KP_9, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0009 } },
  { KEYCODE_KP_4, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0004 } },
  { KEYCODE_KP_5, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0005 } },
  { KEYCODE_KP_6, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0006 } },
  { KEYCODE_KP_1, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0001 } },
  { KEYCODE_KP_2, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0002 } },
  { KEYCODE_KP_3, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0003 } },
  { KEYCODE_KP_0, MODIFIER_ALTGR, FLAG_SYMBOL0, { 0x0000 } },
  { KEYCODE_ESC, 0, FLAG_SYMBOL0, { 0x1b } },
  { KEYCODE_ESC, MODIFIER_ALT, FLAG_SYMBOL0, { 0x1b } },
  { KEYCODE_1, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '1', '!' } },
  { KEYCODE_1, MODIFIER_ALT, FLAG_SYMBOL0, { '1' } },
  { KEYCODE_2, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '2', '@', '2', '"' } },
  { KEYCODE_2, MODIFIER_ALT, FLAG_SYMBOL0, { '2' } },
  { KEYCODE_3, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '3', '#', '3', '?' } },
  { KEYCODE_3, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1b } },
  { KEYCODE_3, MODIFIER_ALT, FLAG_SYMBOL0, { '3' } },
  { KEYCODE_4, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '4', '$', '4', ';' } },
  { KEYCODE_4, MODIFIER_ALT, FLAG_SYMBOL0, { '4' } },
  { KEYCODE_5, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '5', '%', '5', ':' } },
  { KEYCODE_5, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1d } },
  { KEYCODE_5, MODIFIER_ALT, FLAG_SYMBOL0, { '5' } },
  { KEYCODE_6, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '6', '^', '6', ',' } },
  { KEYCODE_6, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1e } },
  { KEYCODE_6, MODIFIER_ALT, FLAG_SYMBOL0, { '6' } },
  { KEYCODE_7, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '7', '&', '7', '.' } },
  { KEYCODE_7, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1f } },
  { KEYCODE_7, MODIFIER_ALT, FLAG_SYMBOL0, { '7' } },
  { KEYCODE_8, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '8', '*' } },
  { KEYCODE_8, MODIFIER_CONTROL, FLAG_STRING0, { keyString0 } },
  { KEYCODE_8, MODIFIER_ALT, FLAG_SYMBOL0, { '8' } },
  { KEYCODE_9, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '9', '(' } },
  { KEYCODE_9, MODIFIER_ALT, FLAG_SYMBOL0, { '9' } },
  { KEYCODE_0, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '0', ')' } },
  { KEYCODE_0, MODIFIER_ALT, FLAG_SYMBOL0, { '0' } },
  { KEYCODE_MINUS, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '-', '_' } },
  { KEYCODE_MINUS, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1f } },
  { KEYCODE_MINUS, MODIFIER_ALT, FLAG_SYMBOL0, { '-' } },
  { KEYCODE_PLUS, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '=', '+' } },
  { KEYCODE_PLUS, MODIFIER_ALT, FLAG_SYMBOL0, { '=' } },
  { KEYCODE_BKSP, 0, FLAG_SYMBOL0, { 0x08 } },
  { KEYCODE_BKSP, MODIFIER_ALT, FLAG_STRING0, { keyString0 } },
  { KEYCODE_TAB, 0, FLAG_SYMBOL0, { 0x09 } },
  { KEYCODE_TAB, MODIFIER_ALT, FLAG_SYMBOL0, { 0x09 } },
  { KEYCODE_Q, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'q', 'Q', 0x0439, 0x0419 } },
  { KEYCODE_Q, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x11 } },
  { KEYCODE_Q, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x11 } },
  { KEYCODE_W, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'w', 'W', 0x0446, 0x0426 } },
  { KEYCODE_W, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x17 } },
  { KEYCODE_W, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x17 } },
  { KEYCODE_E, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'e', 'E', 0x0443, 0x0423 } },
  { KEYCODE_E, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x05 } },
  { KEYCODE_E, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x05 } },
  { KEYCODE_R, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'r', 'R', 0x043a, 0x041a } },
  { KEYCODE_R, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x12 } },
  { KEYCODE_R, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x12 } },
  { KEYCODE_T, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 't', 'T', 0x0435, 0x0415 } },
  { KEYCODE_T, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x14 } },
  { KEYCODE_T, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x14 } },
  { KEYCODE_Y, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'y', 'Y', 0x043d, 0x041d } },
  { KEYCODE_Y, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x19 } },
  { KEYCODE_Y, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x19 } },
  { KEYCODE_U, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'u', 'U', 0x0433, 0x0413 } },
  { KEYCODE_U, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x15 } },
  { KEYCODE_U, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x15 } },
  { KEYCODE_I, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'i', 'I', 0x0448, 0x0428 } },
  { KEYCODE_I, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x09 } },
  { KEYCODE_I, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x09 } },
  { KEYCODE_O, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'o', 'O', 0x0449, 0x0429 } },
  { KEYCODE_O, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0f } },
  { KEYCODE_O, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0f } },
  { KEYCODE_P, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'p', 'P', 0x0437, 0x0417 } },
  { KEYCODE_P, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x10 } },
  { KEYCODE_P, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x10 } },
  { KEYCODE_LBRACE, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '[', '{', 0x0445, 0x0425 } },
  { KEYCODE_LBRACE, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1b } },
  { KEYCODE_LBRACE, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1b } },
  { KEYCODE_LBRACE, MODIFIER_ALT, FLAG_SYMBOL0, { '[' } },
  { KEYCODE_RVRACE, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { ']', '}', '[', ']' } },
  { KEYCODE_RVRACE, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1d } },
  { KEYCODE_RVRACE, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1d } },
  { KEYCODE_RVRACE, MODIFIER_ALT, FLAG_SYMBOL0, { ']' } },
  { KEYCODE_ENTER, 0, FLAG_SYMBOL0, { 0x0d } },
  { KEYCODE_A, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'a', 'A', 0x0444, 0x0424 } },
  { KEYCODE_A, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x01 } },
  { KEYCODE_A, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x01 } },
  { KEYCODE_S, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 's', 'S', 0x044b, 0x042b } },
  { KEYCODE_S, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x13 } },
  { KEYCODE_S, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x13 } },
  { KEYCODE_D, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'd', 'D', 0x0432, 0x0412 } },
  { KEYCODE_D, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x04 } },
  { KEYCODE_D, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x04 } },
  { KEYCODE_F, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'f', 'F', 0x0430, 0x0410 } },
  { KEYCODE_F, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x06 } },
  { KEYCODE_F, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x06 } },
  { KEYCODE_G, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'g', 'G', 0x043f, 0x041f } },
  { KEYCODE_G, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x07 } },
  { KEYCODE_G, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x07 } },
  { KEYCODE_H, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'h', 'H', 0x0440, 0x0420 } },
  { KEYCODE_H, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x08 } },
  { KEYCODE_H, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x08 } },
  { KEYCODE_J, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'j', 'J', 0x043e, 0x041e } },
  { KEYCODE_J, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0a } },
  { KEYCODE_J, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0a } },
  { KEYCODE_K, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'k', 'K', 0x043b, 0x041b } },
  { KEYCODE_K, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0b } },
  { KEYCODE_K, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0b } },
  { KEYCODE_L, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'l', 'L', 0x0434, 0x0414 } },
  { KEYCODE_L, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0c } },
  { KEYCODE_L, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0c } },
  { KEYCODE_SEMI, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { ';', ':', 0x0436, 0x0416 } },
  { KEYCODE_SEMI, MODIFIER_ALT, FLAG_SYMBOL0, { ';' } },
  { KEYCODE_QUOTE, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '\'', '"', 0x044d, 0x042d } },
  { KEYCODE_QUOTE, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x07 } },
  { KEYCODE_QUOTE, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x07 } },
  { KEYCODE_QUOTE, MODIFIER_ALT, FLAG_SYMBOL0, { '\'' } },
  { KEYCODE_TILDE, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '`', '~', 0x044a, 0x042a } },
  { KEYCODE_TILDE, MODIFIER_ALT, FLAG_SYMBOL0, { '`' } },
  { KEYCODE_BSLASH, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '\\', '|' } },
  { KEYCODE_BSLASH, MODIFIER_ALT, FLAG_SYMBOL0, { '\\' } },
  { KEYCODE_Z, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'z', 'Z', 0x044f, 0x042f } },
  { KEYCODE_Z, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1a } },
  { KEYCODE_Z, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x1a } },
  { KEYCODE_X, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'x', 'X', 0x0447, 0x0427 } },
  { KEYCODE_X, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x18 } },
  { KEYCODE_X, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x18 } },
  { KEYCODE_C, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'c', 'C', 0x0441, 0x0421 } },
  { KEYCODE_C, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x03 } },
  { KEYCODE_C, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x03 } },
  { KEYCODE_V, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'v', 'V', 0x043c, 0x041c } },
  { KEYCODE_V, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x16 } },
  { KEYCODE_V, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x16 } },
  { KEYCODE_B, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'b', 'B', 0x0438, 0x0418 } },
  { KEYCODE_B, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x02 } },
  { KEYCODE_B, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x02 } },
  { KEYCODE_N, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'n', 'N', 0x0442, 0x0422 } },
  { KEYCODE_N, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0e } },
  { KEYCODE_N, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0e } },
  { KEYCODE_M, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { 'm', 'M', 0x044c, 0x042c } },
  { KEYCODE_M, MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0d } },
  { KEYCODE_M, MODIFIER_ALTGR | MODIFIER_CONTROL, FLAG_SYMBOL0, { 0x0d } },
  { KEYCODE_COMMA, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { ',', '<', 0x0431, 0x0411 } },
  { KEYCODE_COMMA, MODIFIER_ALT, FLAG_SYMBOL0, { ',' } },
  { KEYCODE_PERIOD, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '.', '>', 0x044e, 0x042e } },
  { KEYCODE_PERIOD, MODIFIER_ALT, FLAG_SYMBOL0, { '.' } },
  { KEYCODE_FSHASH, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1 | FLAG_SYMBOL2 | FLAG_SYMBOL3, { '/', '?', 0x0451, 0x0401 } },
  { KEYCODE_FSHASH, MODIFIER_CONTROL, FLAG_STRING0, { keyString0 } },
  { KEYCODE_FSHASH, MODIFIER_ALT, FLAG_SYMBOL0, { '/' } },
  { KEYCODE_KP_TIMES, 0, FLAG_STRING0, { keyString1 } },
  { KEYCODE_SPACE, 0, FLAG_SYMBOL0, { ' ' } },
  { KEYCODE_SPACE, MODIFIER_ALT, FLAG_SYMBOL0, { ' ' } },
  { KEYCODE_F1, 0, FLAG_STRING0 | FLAG_STRING1, { keyString2, keyString3 } },
  { KEYCODE_F1, MODIFIER_CONTROL, FLAG_STRING0, { keyString2 } },
  { KEYCODE_F2, 0, FLAG_STRING0 | FLAG_STRING1, { keyString4, keyString5 } },
  { KEYCODE_F2, MODIFIER_CONTROL, FLAG_STRING0, { keyString4 } },
  { KEYCODE_F3, 0, FLAG_STRING0 | FLAG_STRING1, { keyString6, keyString7 } },
  { KEYCODE_F3, MODIFIER_CONTROL, FLAG_STRING0, { keyString6 } },
  { KEYCODE_F4, 0, FLAG_STRING0 | FLAG_STRING1, { keyString8, keyString9 } },
  { KEYCODE_F4, MODIFIER_CONTROL, FLAG_STRING0, { keyString8 } },
  { KEYCODE_F5, 0, FLAG_STRING0 | FLAG_STRING1, { keyString10, keyString11 } },
  { KEYCODE_F5, MODIFIER_CONTROL, FLAG_STRING0, { keyString10 } },
  { KEYCODE_F6, 0, FLAG_STRING0 | FLAG_STRING1, { keyString12, keyString13 } },
  { KEYCODE_F6, MODIFIER_CONTROL, FLAG_STRING0, { keyString12 } },
  { KEYCODE_F7, 0, FLAG_STRING0 | FLAG_STRING1, { keyString14, keyString15 } },
  { KEYCODE_F7, MODIFIER_CONTROL, FLAG_STRING0, { keyString14 } },
  { KEYCODE_F8, 0, FLAG_STRING0 | FLAG_STRING1, { keyString16, keyString17 } },
  { KEYCODE_F8, MODIFIER_CONTROL, FLAG_STRING0, { keyString16 } },
  { KEYCODE_F9, 0, FLAG_STRING0 | FLAG_STRING1, { keyString18, keyString19 } },
  { KEYCODE_F9, MODIFIER_CONTROL, FLAG_STRING0, { keyString18 } },
  { KEYCODE_F10, 0, FLAG_STRING0 | FLAG_STRING1, { keyString20, keyString21 } },
  { KEYCODE_F10, MODIFIER_CONTROL, FLAG_STRING0, { keyString20 } },
  { KEYCODE_NUM, 0, FLAG_STRING0, { keyString22 } },
  { KEYCODE_SCROLL, 0, FLAG_SYMBOL0, { 0x14 } },
  { KEYCODE_SCROLL, MODIFIER_ALT, FLAG_SYMBOL0, { 0x14 } },
  { KEYCODE_KP_7, 0, FLAG_STRING0, { keyString23 } },
  { KEYCODE_KP_8, 0, FLAG_STRING0, { keyString24 } },
  { KEYCODE_KP_9, 0, FLAG_STRING0, { keyString25 } },
  { KEYCODE_KP_MINUS, 0, FLAG_STRING0, { keyString26 } },
  { KEYCODE_KP_4, 0, FLAG_STRING0, { keyString27 } },
  { KEYCODE_KP_5, 0, FLAG_STRING0, { keyString28 } },
  { KEYCODE_KP_6, 0, FLAG_STRING0, { keyString29 } },
  { KEYCODE_KP_PLUS, 0, FLAG_STRING0, { keyString30 } },
  { KEYCODE_KP_1, 0, FLAG_STRING0, { keyString31 } },
  { KEYCODE_KP_2, 0, FLAG_STRING0, { keyString32 } },
  { KEYCODE_KP_3, 0, FLAG_STRING0, { keyString33 } },
  { KEYCODE_KP_0, 0, FLAG_STRING0, { keyString34 } },
  { KEYCODE_KP_PERIOD, 0, FLAG_STRING0, { keyString35 } },
  { 0x61, 0, FLAG_SYMBOL0 | FLAG_SYMBOL1, { '<', '>' } },
  { 0x61, MODIFIER_ALT, FLAG_SYMBOL0, { '<' } },
  { KEYCODE_F11, 0, FLAG_STRING0, { keyString3 } },
  { KEYCODE_F11, MODIFIER_CONTROL, FLAG_STRING0, { keyString3 } },
  { KEYCODE_F12, 0, FLAG_STRING0, { keyString5 } },
  { KEYCODE_F12, MODIFIER_CONTROL, FLAG_STRING0, { keyString5 } },
  { KEYCODE_KP_EN, 0, FLAG_STRING0, { keyString30 } },
  { KEYCODE_KP_FSLASH, 0, FLAG_STRING0, { keyString36 } },
  { KEYCODE_HOME, 0, FLAG_STRING0, { keyString37 } },
  { KEYCODE_UP, 0, FLAG_STRING0, { keyString38 } },
  { KEYCODE_PG_UP, 0, FLAG_STRING0, { keyString39 } },
  { KEYCODE_LEFT, 0, FLAG_STRING0, { keyString40 } },
  { KEYCODE_RIGHT, 0, FLAG_STRING0, { keyString41 } },
  { KEYCODE_END, 0, FLAG_STRING0, { keyString42 } },
  { KEYCODE_DOWN, 0, FLAG_STRING0, { keyString43 } },
  { KEYCODE_PG_DN, 0, FLAG_STRING0, { keyString44 } },
  { KEYCODE_INSERT, 0, FLAG_STRING0, { keyString45 } },
  { KEYCODE_DELETE, 0, FLAG_STRING0, { keyString0 } },
};

size_t keyCount = sizeof(keys) / sizeof(keys[0]);

